# Generated by Django 3.1.5 on 2021-01-26 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lavaggi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lavaggio',
            old_name='date',
            new_name='data_lavaggio',
        ),
        migrations.AddField(
            model_name='lavaggio',
            name='video_lavaggio',
            field=models.FileField(default=django.utils.timezone.now, upload_to='store_wash/'),
            preserve_default=False,
        ),
    ]
